### ISSUE TITLE
☂️ [Umbrella Issue] v3.1 Roadmap

### ISSUE THREAD

**Issue by angeloashmore** [angeloashmore/gatsby-source-prismic#224]
v3.1 will focus on two main improvements:

- **Easier preview setup** - Use first-class higher-order components to setup previews.
- **More robust preview features** - Option to build using a specific release ID + official Prismic toolbar support
- **Unlimited Imgix image customization** - Full support of [all Imgix parameters](https://docs.imgix.com/apis/url) via `gatsby-plugin-imgix`.

###  Easier preview setup

- [x] Improved preview setup with HOCs. See #223.
- [x] Document preview HOCs.
- [x] Improved previews with Prismic Toolbar support. See #210.

###  More robust preview features

- [x] Add `releaseID` option (#228)
- [x] Add official Prismic toolbar support (#210)

### Unlimited Imgix image customization

- [x] Replace Imgix image handling with `gatsby-plugin-imgix` to allow total customization. See [`gatsby-plugin-imgix`](https://www.gatsbyjs.org/packages/gatsby-plugin-imgix/).
- [x] Document Imgix fields.
